<a href="https://colab.research.google.com/github/Dkolomy/BMV-Research/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Resource: https://github.com/Dkolomy/pytorch-deep-learning
### Book: https://www.learnpytorch.io/
### Docs: https://docs.pytorch.org/docs/stable/index.html

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

### Random tensors

In [16]:
random_tensor = torch.rand(4, 3, 2)
random_tensor

tensor([[[0.3564, 0.7877],
         [0.1409, 0.2837],
         [0.3336, 0.5373]],

        [[0.5295, 0.4242],
         [0.1912, 0.2644],
         [0.1619, 0.8603]],

        [[0.5686, 0.1769],
         [0.8358, 0.3008],
         [0.5387, 0.0569]],

        [[0.8401, 0.8332],
         [0.4327, 0.3150],
         [0.2312, 0.1534]]])

In [17]:
random_tensor.ndim

3

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_hundred = torch.arange(start=0, end=1000, step=77)
one_to_hundred

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2704, 0.9335, 0.7658, 0.6493],
        [0.1508, 0.9197, 0.8637, 0.2527],
        [0.1310, 0.5220, 0.1538, 0.0552]])

In [26]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2704, 0.9335, 0.7658, 0.6493],
        [0.1508, 0.9197, 0.8637, 0.2527],
        [0.1310, 0.5220, 0.1538, 0.0552]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [27]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,requires_grad=False)
float_tensor

tensor([3., 6., 9.])

### Tensor datatypes
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get  device from a tensor, can use `tensor.device`

In [28]:
tensor = torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [29]:
torch.matmul(tensor,tensor)

tensor(14)

In [30]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.8 ms, sys: 1.17 ms, total: 2.97 ms
Wall time: 10.3 ms


In [31]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 923 µs, sys: 0 ns, total: 923 µs
Wall time: 941 µs


tensor(14)

1. Tthe **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`
3. http://matrixmultiplication.xyz/


In [32]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

tensor_A.shape, tensor_B.shape

# torch.matmul(tensor_A, tensor_B) or torch.mm(tensor_A, tensor_B) -> error
# manupulate shapes -> transpose (tensor_B.T)

tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

### Matrix multiplication
https://mathsisfun.com/algebra/matrix-multiplying.html
1. Element-wize multiplications
2. Matrix multiplications

In [33]:
### Element wize multiplication
tensor = torch.tensor([1,2,3])
tensor * tensor

tensor([1, 4, 9])

In [34]:
### Matrix multiplication
### tensor = torch.tensor([1,2,3])
### 1*1 + 2*2 + 3*3 = 14
torch.matmul(tensor, tensor)

tensor(14)

## Tensor aggregation

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [38]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [40]:
# Position
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [41]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

## Reshaping, stacking ,squeezing and unsqueezing tensors

* Reshaping - reshqpes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
^ Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
https://docs.pytorch.org/docs/2.11/generated/torch.stack.html
https://docs.pytorch.org/docs/2.12/generated/torch.vstack.html
https://docs.pytorch.org/docs/2.12/generated/torch.hstack.html
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in a certain way



In [74]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
x1 = x.reshape(10,1)
x1, x1.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [66]:
x2 = x1.reshape(5,2)
x2, x2.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [72]:
z = x1.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [73]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [75]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [85]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [76]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# Changing z changes x (because a view of a tensor shapes the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [83]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [89]:
# torch.squeeze() - remove all single dimentions from a target tensor
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
x_squeeze = x_reshaped.squeeze()
x_squeeze, x_squeeze.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [96]:
# torch.squeeae() - removes all single dimentions from a target tensor
# https://docs.pytorch.org/docs/2.12/generated/torch.squeeze.html
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [97]:
# torch.unsqueese() - adds a single dimention to a target tensor at specific dim (dimention)
# https://docs.pytorch.org/docs/2.12/generated/torch.unsqueeze.html
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remove extra dimentions from x_reshaped
# https://docs.pytorch.org/docs/2.12/generated/torch.reshape.html
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
#

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [100]:
# torch.permute - rearrages the dimentions of a target tensor in a specified order
# https://docs.pytorch.org/docs/2.12/generated/torch.permute.html
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


http://matrixmultiplication.xyz/

## Indexing (selecting data from tensors)
### Indexing with PyTorch is similar to indexing with NumPy


In [1]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [4]:
x[0][0][0]

tensor(1)

In [6]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [9]:
# Get all values of 9th and 1st dimensions but only index 1 of 2nd dimension
x[:, : , 1]

tensor([[2, 5, 8]])

In [10]:
x[:, 1, 1]

tensor([5])

In [11]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [15]:
# Index on x to return 9
x[0][2][2]

# Index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

In [45]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [47]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1490, 0.4593, 0.7263, 0.2366],
        [0.7210, 0.2485, 0.5867, 0.1365],
        [0.7993, 0.7189, 0.7523, 0.6593]])
tensor([[0.7128, 0.6237, 0.4599, 0.2311],
        [0.6526, 0.3838, 0.9078, 0.0986],
        [0.3823, 0.9313, 0.0116, 0.1071]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [48]:
RANDON_SEED = 42
torch.manual_seed(RANDON_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDON_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch on GPU's
GPU = faster compuattipn on numbers, thanks to CUDA + NVIDIA hardware + PyTorch

In [49]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [50]:
# Chack for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [51]:
torch.cuda.device_count()

0