<a href="https://colab.research.google.com/github/Dkolomy/BMV-Research/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Resource: https://github.com/Dkolomy/pytorch-deep-learning
### Book: https://www.learnpytorch.io/
### Docs: https://docs.pytorch.org/docs/stable/index.html

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

### Random tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6617, 0.6587, 0.9090, 0.2809],
        [0.4688, 0.1020, 0.5817, 0.3663],
        [0.9249, 0.3187, 0.3208, 0.6581]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_hundred = torch.arange(start=0, end=1000, step=77)
one_to_hundred

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0826, 0.0271, 0.3358, 0.6969],
        [0.5585, 0.2111, 0.6953, 0.9376],
        [0.7696, 0.6888, 0.1218, 0.7598]])

In [26]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0826, 0.0271, 0.3358, 0.6969],
        [0.5585, 0.2111, 0.6953, 0.9376],
        [0.7696, 0.6888, 0.1218, 0.7598]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [27]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,requires_grad=False)
float_tensor

tensor([3., 6., 9.])

In [28]:
tensor = torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [29]:
torch.matmul(tensor,tensor)

tensor(14)

In [30]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.07 ms, sys: 0 ns, total: 2.07 ms
Wall time: 6.21 ms


In [31]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 539 µs, sys: 0 ns, total: 539 µs
Wall time: 459 µs


tensor(14)

1. Tthe **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`
3. http://matrixmultiplication.xyz/


In [32]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

tensor_A.shape, tensor_B.shape

# torch.matmul(tensor_A, tensor_B) or torch.mm(tensor_A, tensor_B) -> error
# manupulate shapes -> transpose (tensor_B.T)

tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Tensor aggregation

In [33]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [35]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [36]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [37]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [38]:
# Position
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [39]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [40]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [41]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [42]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

## PyTorch tensors & NumPy

In [43]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [44]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [45]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7271, 0.8038, 0.8711, 0.8778],
        [0.0269, 0.3311, 0.3146, 0.6715],
        [0.7978, 0.1832, 0.9786, 0.2257]])
tensor([[0.8922, 0.4330, 0.3154, 0.8401],
        [0.9775, 0.0742, 0.1056, 0.3507],
        [0.8815, 0.6750, 0.9930, 0.1379]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [49]:
RANDON_SEED = 42
torch.manual_seed(RANDON_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDON_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch on GPU's
GPU = faster compuattipn on numbers, thanks to CUDA + NVIDIA hardware + PyTorch

In [1]:
!nvidia-smi

Sun Dec  7 01:33:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Chack for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
torch.cuda.device_count()

1