<a href="https://colab.research.google.com/github/Dkolomy/BMV-Research/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Resource: https://github.com/Dkolomy/pytorch-deep-learning
### Book: https://www.learnpytorch.io/
### Docs: https://docs.pytorch.org/docs/stable/index.html

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

### Random tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4615, 0.3077, 0.2490, 0.9947],
        [0.1033, 0.4975, 0.5337, 0.1809],
        [0.8562, 0.1577, 0.1122, 0.1084]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_hundred = torch.arange(start=0, end=1000, step=77)
one_to_hundred

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1299, 0.2165, 0.4520, 0.9532],
        [0.1197, 0.4187, 0.5640, 0.4134],
        [0.6930, 0.0619, 0.5023, 0.1698]])

In [26]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1299, 0.2165, 0.4520, 0.9532],
        [0.1197, 0.4187, 0.5640, 0.4134],
        [0.6930, 0.0619, 0.5023, 0.1698]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [27]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,requires_grad=False)
float_tensor

tensor([3., 6., 9.])

In [28]:
tensor = torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [29]:
torch.matmul(tensor,tensor)

tensor(14)

In [30]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.28 ms, sys: 87 µs, total: 2.36 ms
Wall time: 8.58 ms


In [31]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.05 ms, sys: 5 µs, total: 1.05 ms
Wall time: 1.83 ms


tensor(14)

1. Tthe **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`
3. http://matrixmultiplication.xyz/


In [32]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

tensor_A.shape, tensor_B.shape

# torch.matmul(tensor_A, tensor_B) or torch.mm(tensor_A, tensor_B) -> error
# manupulate shapes -> transpose (tensor_B.T)

tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Tensor aggregation

In [33]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [35]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [38]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [40]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [41]:
# Position
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [42]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [45]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))