<a href="https://colab.research.google.com/github/Dkolomy/BMV-Research/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Resource: https://github.com/Dkolomy/pytorch-deep-learning
### Book: https://www.learnpytorch.io/
### Docs: https://docs.pytorch.org/docs/stable/index.html

In [53]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors

### Creating tensors

In [54]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [55]:
scalar.ndim

0

In [56]:
scalar.item()

7

In [57]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [58]:
vector.ndim

1

In [59]:
vector.shape

torch.Size([2])

In [60]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [61]:
MATRIX.ndim

2

In [62]:
MATRIX[0]

tensor([7, 8])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [65]:
TENSOR.ndim

3

In [66]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

### Random tensors

In [68]:
random_tensor = torch.rand(4, 3, 2)
random_tensor

tensor([[[0.8972, 0.2738],
         [0.6454, 0.6370],
         [0.4980, 0.2562]],

        [[0.0834, 0.7741],
         [0.3734, 0.5345],
         [0.2871, 0.5593]],

        [[0.9151, 0.8235],
         [0.0116, 0.3489],
         [0.6723, 0.6014]],

        [[0.1528, 0.4892],
         [0.5599, 0.8947],
         [0.3540, 0.9732]]])

In [69]:
random_tensor.ndim

3

In [70]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [71]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [73]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [74]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
one_to_hundred = torch.arange(start=0, end=1000, step=77)
one_to_hundred

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [76]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5252, 0.0032, 0.7222, 0.8352],
        [0.8246, 0.7982, 0.5738, 0.5555],
        [0.7402, 0.8254, 0.0608, 0.5877]])

In [78]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5252, 0.0032, 0.7222, 0.8352],
        [0.8246, 0.7982, 0.5738, 0.5555],
        [0.7402, 0.8254, 0.0608, 0.5877]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [79]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,requires_grad=False)
float_tensor

tensor([3., 6., 9.])

### Tensor datatypes
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get  device from a tensor, can use `tensor.device`

In [80]:
tensor = torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [81]:
torch.matmul(tensor,tensor)

tensor(14)

In [82]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.29 ms, sys: 48 µs, total: 1.34 ms
Wall time: 1.16 ms


In [83]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 294 µs, sys: 52 µs, total: 346 µs
Wall time: 274 µs


tensor(14)

1. Tthe **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`
3. http://matrixmultiplication.xyz/


In [84]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

tensor_A.shape, tensor_B.shape

# torch.matmul(tensor_A, tensor_B) or torch.mm(tensor_A, tensor_B) -> error
# manupulate shapes -> transpose (tensor_B.T)

tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

### Matrix multiplication
https://mathsisfun.com/algebra/matrix-multiplying.html
1. Element-wize multiplications
2. Matrix multiplications

In [85]:
### Element wize multiplication
tensor = torch.tensor([1,2,3])
tensor * tensor

tensor([1, 4, 9])

In [86]:
### Matrix multiplication
### tensor = torch.tensor([1,2,3])
### 1*1 + 2*2 + 3*3 = 14
torch.matmul(tensor, tensor)

tensor(14)

## Tensor aggregation

In [87]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [89]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [90]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [91]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [92]:
# Position
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [93]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [94]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

## Reshaping, stacking ,squeezing and unsqueezing tensors

* Reshaping - reshqpes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
^ Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
https://docs.pytorch.org/docs/2.11/generated/torch.stack.html
https://docs.pytorch.org/docs/2.12/generated/torch.vstack.html
https://docs.pytorch.org/docs/2.12/generated/torch.hstack.html
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in a certain way



In [95]:
import torch
x = torch.arange(0., 10.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [96]:
x1 = x.reshape(10,1)
x1, x1.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [97]:
x2 = x1.reshape(5,2)
x2, x2.shape

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.],
         [8., 9.]]),
 torch.Size([5, 2]))

In [98]:
z = x1.view(1,10)
z, z.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [99]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [100]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [101]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 torch.Size([2, 5]))

In [102]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [103]:
# Changing z changes x (because a view of a tensor shapes the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [104]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [105]:
# torch.squeeze() - remove all single dimentions from a target tensor
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [106]:
x_squeeze = x_reshaped.squeeze()
x_squeeze, x_squeeze.shape

(tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [107]:
# torch.squeeae() - removes all single dimentions from a target tensor
# https://docs.pytorch.org/docs/2.12/generated/torch.squeeze.html
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



Previous tensor: tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([10])


In [108]:
# torch.unsqueese() - adds a single dimention to a target tensor at specific dim (dimention)
# https://docs.pytorch.org/docs/2.12/generated/torch.unsqueeze.html
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remove extra dimentions from x_reshaped
# https://docs.pytorch.org/docs/2.12/generated/torch.reshape.html
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
#

Previous tensor: tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([10])

New tensor: tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 10])


In [109]:
# torch.permute - rearrages the dimentions of a target tensor in a specified order
# https://docs.pytorch.org/docs/2.12/generated/torch.permute.html
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


http://matrixmultiplication.xyz/

## Indexing (selecting data from tensors)
### Indexing with PyTorch is similar to indexing with NumPy


In [110]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [111]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [112]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [113]:
x[0][0][0]

tensor(1)

In [114]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [115]:
# Get all values of 9th and 1st dimensions but only index 1 of 2nd dimension
x[:, : , 1]

tensor([[2, 5, 8]])

In [116]:
x[:, 1, 1]

tensor([5])

In [117]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [118]:
# Index on x to return 9
x[0][2][2]

# Index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [119]:
# https://docs.pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [120]:
# Change the value of array, what will this do to `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [121]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`

TO reduce the randomness in neural networks and PyTorch comes the concept of a random seed.
Essentially what the random seed does is "Flavour" the randomness

In [122]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0711, 0.0810, 0.6485, 0.6471],
        [0.2050, 0.8491, 0.6927, 0.3903],
        [0.7509, 0.0852, 0.0563, 0.3541]])
tensor([[0.3154, 0.9177, 0.4249, 0.9429],
        [0.0373, 0.1161, 0.1155, 0.3083],
        [0.2552, 0.0182, 0.6257, 0.3690]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [123]:
# Let's make some randombut reproducible tensors

RANDON_SEED = 42
torch.manual_seed(RANDON_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDON_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch on GPU's
GPU = faster compuattipn on numbers, thanks to CUDA + NVIDIA hardware + PyTorch

In [124]:
!nvidia-smi

Tue May 19 00:25:07 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [125]:
# Chack for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [127]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [126]:
torch.cuda.device_count()

1