<a href="https://colab.research.google.com/github/Dkolomy/BMV-Research/blob/main/pytorch_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exerciser & Extra-curriculum

In [1]:
import torch
tensor_A = torch.rand(7,7)
tensor_A

tensor([[0.4594, 0.6654, 0.5612, 0.0147, 0.4258, 0.4339, 0.6230],
        [0.9692, 0.8491, 0.2517, 0.7765, 0.5348, 0.4108, 0.1904],
        [0.5102, 0.6265, 0.8265, 0.7271, 0.3885, 0.8913, 0.3826],
        [0.1645, 0.3211, 0.7858, 0.4292, 0.7412, 0.0097, 0.0117],
        [0.9982, 0.2597, 0.3901, 0.9906, 0.1188, 0.9313, 0.4859],
        [0.1232, 0.1607, 0.8069, 0.4280, 0.4018, 0.1490, 0.6238],
        [0.2462, 0.9276, 0.8721, 0.7257, 0.9224, 0.8928, 0.9223]])

In [2]:
tensor_B = torch.rand(1,7)
tensor_B

tensor([[0.3076, 0.8945, 0.4321, 0.3439, 0.0284, 0.7663, 0.5320]])

In [3]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[1.6601],
        [1.8647],
        [2.2221],
        [0.8597],
        [2.0240],
        [1.1349],
        [2.7329]])

In [6]:
torch.manual_seed(2)
X=torch.rand(size=(7,7))
Y=torch.rand(size=(1,7))
Z=torch.matmul(X,Y.T)
Z, Z.shape


(tensor([[2.5722],
         [2.0592],
         [2.2192],
         [2.4909],
         [1.5547],
         [1.6152],
         [3.0816]]),
 torch.Size([7, 1]))

In [7]:
max=torch.max(Z)
min=torch.min(Z)
max, min

(tensor(3.0816), tensor(1.5547))

In [8]:
arg_max=torch.argmax(Z)
arg_min=torch.argmin(Z)
arg_max, arg_min

(tensor(6), tensor(4))

In [10]:
torch.manual_seed(7)
tensor_D=torch.rand(1,1,1,10)
tensor_E=tensor_D.squeeze()

print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
